GOOGLE = "GOOGLE"
BING = "BING"
PERFORMMEDIA = "PERFORMMEDIA"
MEDIAALPHA = "MEDIAALPHA"
FACEBOOK = "FACEBOOK"
SUREHITS = "SUREHITS"
TABOOLA = "TABOOLA"
YAHOO = "YAHOO"
MAJOR_TRAFFIC_SOURCES = [
    GOOGLE,BING,PERFORMMEDIA,MEDIAALPHA,FACEBOOK,
#     SUREHITS,
    TABOOLA,
#     YAHOO,
]

U65 = "HEALTH"
O65 = 'MEDICARE'
PRODUCTS = [U65,O65]
TABOOLA_OS_DOMAIN = ['Mac_OS_X', 'Linux', 'Windows', 'iOS', 'iPadOS', 'Android']