name: bing-update-bids-tod

on:
  push:
    branches: [ workspace_amal ]
    paths:
      - models/bing/time_of_day/**
      - .github/workflows/bing_update_bids_tod.yml
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-keyword-bids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Activate conda env from .yml
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda-data-science-bing.yml

      - name: Install pip packages
        run: |
          echo "${GIT_SSH_KEY}\n" > GIT_SSH_PTH
          chmod 600 GIT_SSH_PTH
          GIT_SSH_COMMAND="ssh -i GIT_SSH_PTH" pip install -r ${GITHUB_WORKSPACE}/requirements.txt
        env:
          GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}

      - name: Compute updated bids
        id: compute
        run: |
          python ${GITHUB_WORKSPACE}/compute_keyword_bid_updates.py || exit_code=$?
          echo "::set-output name=exit_code::$exit_code" # https://stackoverflow.com/questions/60453924
          exit $exit_code

      - name: Check updated bids
        id: check
        run: |
          python ${GITHUB_WORKSPACE}/check_keyword_bid_updates.py || exit_code=$?
          echo "::set-output name=exit_code::$exit_code" # https://stackoverflow.com/questions/60453924
          exit $exit_code
          
      - name: Apply updated bids
        id: apply
        run: |
          python ${GITHUB_WORKSPACE}/apply_keyword_bid_updates.py || exit_code=$?
          echo "::set-output name=exit_code::$exit_code" # https://stackoverflow.com/questions/60453924
          exit $exit_code
      
      - name: Compute failure notification
        uses: rtCamp/action-slack-notify@v2
        if: always() && steps.compute.outputs.exit_code > 0
        env:
          SLACK_CHANNEL: alert-test
          SLACK_MESSAGE: <!channel>
          SLACK_COLOR: ${{ fromJSON('["good","danger","warning"]')[steps.compute.outputs.exit_code] }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions

      - name: Check failure notification
        uses: rtCamp/action-slack-notify@v2
        if: always() && steps.check.outputs.exit_code > 0
        env:
          SLACK_CHANNEL: alert-test
          SLACK_MESSAGE: <!channel>
          SLACK_COLOR: ${{ fromJSON('["good","danger","warning"]')[steps.check.outputs.exit_code] }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions

      - name: Apply failure notification
        uses: rtCamp/action-slack-notify@v2
        if: always() && steps.apply.outputs.exit_code > 0
        env:
          SLACK_CHANNEL: alert-test
          SLACK_MESSAGE: <!channel>
          SLACK_COLOR: ${{ fromJSON('["good","danger","warning"]')[steps.apply.outputs.exit_code] }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions

      - name: Job success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: alert-test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions
          SLACK_MESSAGE: Bing keyword bids updated successfully!