name: taboola-retrain

on:
  push:
    branches: 
      # - workspace_amal
    #   - main
      - workflow_test
    paths:
      - models/taboola/**
      - .github/workflows/taboola_retrain.yml
  
  schedule:
  - cron: "0 10 1 * *" # monthly @ 6 am EST
  
  workflow_dispatch:
    inputs:
      execution_date:
        required: true

jobs:
  retrain:
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL: alert-test
      # SLACK_CHANNEL: adtech-alerts
      CHANNEL_SID: '!channel'
      AMAL_SID: '@U01PPS0BLKY'
      # CURTIS_SID: '@U01MYTF7X18'
      # DAN_SID: '@U01R2UV56Q1'
      
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Activate conda env from .yml
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: models/taboola/conda.yml

      - name: Install pip packages
        run: |
          echo "${GIT_SSH_KEY}\n" > GIT_SSH_PTH
          chmod 600 GIT_SSH_PTH
          GIT_SSH_COMMAND="ssh -i GIT_SSH_PTH" \
            pip install -r ${GITHUB_WORKSPACE}/models/taboola/requirements.txt
          pip freeze
        env:
          GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}

      - name: Retrain bid model
        run: |
          exit 1
          export PYTHONPATH=${GITHUB_WORKSPACE}:${PYTHONPATH}
          python ${GITHUB_WORKSPACE}/models/taboola/compute_bids_train.py
      
      - name: Success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          SLACK_MESSAGE: \
            <${{ env.AMAL_SID }}> Taboola bid model train SUCCESS!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions

      - name: Failure notification
        uses: rtCamp/action-slack-notify@v2
        if: cancelled() || failure()
        env:
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          SLACK_MESSAGE: \
            <${{ env.AMAL_SID }}> Taboola bid model train FAILURE!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://cdn.healthcare.com/devops/logos/GitHub-Mark-64px.png
          SLACK_USERNAME: GithubActions
          SLACK_COLOR: 'danger'
